### ISSUE TITLE
Change Server Action Error with download.py

### ISSUE THREAD

**Issue by leo-s-z** [google/glazier#208]
Hello, 
When I use the command ChangeServer the config path is broken up with /. For example instead of the config path being  **/new/config/path** it becomes **/n/e/w/c/o/n/f/i/g/p/a/t/h** and causes an error when it tries to download the new build file. 

I believe the issue is line 115 in download.py, when I remove the / and leave it blank the imaging resumes. 

`sub_path = '/'.join(sub_path).strip('/')
`
`sub_path = ''.join(sub_path).strip('/')
`

**Comment by TsekNet** [comment]
Hi! Thanks for submitting this issue. 

Can you post the YAML config that you're using when invoking the ChangeServer action?

**Comment by leo-s-z** [comment]
Hello, 

Below is the YAML config I'm using. 

```
templates:
    
controls:
 
#Show Menu
  - include:
    - ['/', 'menu.yaml'] 

  - pin:
      'USER_server': ['ca']  
    ChangeServer: ['https://DCCMIS05:8443', '/config/init']
  - pin:
      'USER_server': ['can']  
    ChangeServer: ['https://CAN-IMG-GLZ-000:8443', '/config/init']
  - pin:
      'USER_server': ['nj']  
    ChangeServer: ['https://NJ-IMG-GLZ-000:8443', '/config/init']
  - pin:
      'USER_server': ['ny']  
    ChangeServer: ['https://NY-IMG-GLZ-000:8443', '/config/init']
    
```
